/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const Config = t.iface([], {
  "prefix": "string",
});

const exportedTypeSuite: t.ITypeSuite = {
  Config,
};
export default exportedTypeSuite;
